CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'resume') THEN
        CREATE SCHEMA resume;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'resume') THEN
        CREATE SCHEMA resume;
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA resume;

CREATE TABLE resume.resume (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    object_id uuid NOT NULL DEFAULT (resume.uuid_generate_v4()),
    name character varying(300) NOT NULL,
    birth_date date NOT NULL,
    salary bigint NOT NULL,
    city text NOT NULL,
    expertise character varying(1000) NOT NULL,
    skills character varying(1000) NOT NULL,
    deleted boolean NOT NULL DEFAULT FALSE,
    created timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    create_user_id uuid NOT NULL,
    CONSTRAINT pk_resume PRIMARY KEY (id)
);

CREATE INDEX ix_resume_create_user_id ON resume.resume (create_user_id);

CREATE INDEX ix_resume_created ON resume.resume (created);

CREATE INDEX ix_resume_name ON resume.resume (name);

CREATE UNIQUE INDEX ix_resume_object_id ON resume.resume (object_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250119182820_InitialMigration', '8.0.11');

COMMIT;

